### ISSUE TITLE
能否通过安卓手机安装Python环境 来执行源代码 

### ISSUE THREAD

**Issue by somewheve** [tobyqin/kog-money#10]
如题
实现脱离电脑 来进行运行脚本

**Comment by tobyqin** [comment]
如果只是刷金币是可以的，你可以看一下这个项目：
- https://github.com/openatx/uiautomator2

我用过一段时间，手机装好qpython3 + u2 后，就可以在qpython3里跑kog.py。环境会有一点难弄，稳定性也不是很好，愿意折腾你可以试试。

**Comment by tobyqin** [comment]
上面说的kog.py也不是这个项目里的，需要稍微修改一些，用u2里的方法去模拟点击，坐标是一样的。必要的地方调整一下延迟。

**Comment by JaysonAlbert** [comment]
如果要刷熟练度的话，建议还是用电脑，因为实体机还不兼容不同屏幕尺寸。而且，这个要刷挺久的，总不能一直占着手机

**Comment by somewheve** [comment]
感觉本质上安卓手机是linux系统 感觉还是有点搞头的

**Comment by somewheve** [comment]
我试试root后安装Python环境可不可以

**Comment by tobyqin** [comment]
> 我试试root后安装Python环境可不可以

不用root也可以装python环境。qpython了解一下。
另外Android不是arm的linux，很多软件需要自己编译，不能直接用，root后可玩性多一点，比如搭web server，搞代理。
