### ISSUE TITLE
python money.py时报错，已经安装了adb，并add to path了

### ISSUE THREAD

**Issue by xlzy520** [tobyqin/kog-money#13]
RuntimeError: ERROR: connecting to 127.0.0.1:5038 [WinError 10061] 由于目标计算机积极拒绝，无法连接。.
Is adb running on your computer?

**Comment by tobyqin** [comment]
这是模拟器版的，你确保模拟器什么的跟介绍里配置的一样。

**Comment by xlzy520** [comment]
@tobyqin 配置是一样的，雷电模拟器

**Comment by tobyqin** [comment]
@JaysonAlbert  你也许知道？这应该是环境问题。

**Comment by xlzy520** [comment]
@tobyqin  我用adb devices，显示port是5555，而不是你配好的5038。
我改成5555之后不报错了，但是无效。

**Comment by tobyqin** [comment]
时效已过
