### ISSUE TITLE
有iPhone 6sp 的配置麽？

### ISSUE THREAD

**Issue by yanmin7857** [tobyqin/kog-money#3]
[我直接跑ios那个脚本，坐标错乱。有6sp 的配置麽？
![image](https://user-images.githubusercontent.com/32626749/38967672-bd9db908-43ba-11e8-9cc4-3932c0a2f84e.png)
这样还是无法点中闯关按钮

**Comment by tobyqin** [comment]
我没有6SP，其实你可以自己获取坐标。
手机截图，然后到windows画图软件打开图片，点击对应位置左下角状态栏会出现坐标，应该不少看图软件都可以轻松找到坐标。
